FROM php:{{PHP_VERSION}}-fpm
WORKDIR /var/www

################################################################################
##
##      Install dependencies
##
RUN apt-get update \
    && apt-get install -y sqlite3 mariadb-client libjpeg-dev libpng-dev libonig-dev libzip-dev libicu-dev unzip git \
        && docker-php-ext-install     bcmath pdo_mysql pcntl intl zip \
        && docker-php-ext-configure   gd --with-jpeg  \
        && docker-php-ext-install     gd  \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

USER    33
EXPOSE  9000
CMD     ["php-fpm"]
